check_args
/* Autogenerated */
/* curve description: p224 */
/* requested operations: (all) */
/* s = 0x100000000000000000000000000000000000000000000000000000000 (from "2^224") */
/* c = [(79228162514264337593543950336, 1), (1, -1)] (from "2^96,1;1,-1") */
/* machine_wordsize = 64 (from "64") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (s-c), and also */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */

#include <stdint.h>
typedef unsigned char fiat_p224_uint1;
typedef signed char fiat_p224_int1;
typedef signed __int128 fiat_p224_int128;
typedef unsigned __int128 fiat_p224_uint128;



In check_args
/* Autogenerated */
/* curve description: p224 */
/* requested operations: (all) */
/* s = 0x100000000000000000000000000000000000000000000000000000000 (from "2^224") */
/* c = [(79228162514264337593543950336, 1), (1, -1)] (from "2^96,1;1,-1") */
/* machine_wordsize = 64 (from "64") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (s-c), and also */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */

#include <stdint.h>
typedef unsigned char fiat_p224_uint1;
typedef signed char fiat_p224_int1;
typedef signed __int128 fiat_p224_int128;
typedef unsigned __int128 fiat_p224_uint128;
: Value not < (m ≤ eval saturated_upper_bounds) : expected 115792089237316195423570985008687907853269984665640564039457584007913129639935 < 26959946667150639794667015087019630673557916260026308143510066298881

