check_args
/* Autogenerated */
/* curve description: p384 */
/* requested operations: (all) */
/* s = 0x1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 (from "2^384") */
/* c = [(340282366920938463463374607431768211456, 1), (79228162514264337593543950336, 1), (4294967296, -1), (1, 1)] (from "2^128,1;2^96,1;2^32,-1;1,1") */
/* machine_wordsize = 32 (from "32") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (s-c), and also */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */

#include <stdint.h>
typedef unsigned char fiat_p384_uint1;
typedef signed char fiat_p384_int1;



In check_args
/* Autogenerated */
/* curve description: p384 */
/* requested operations: (all) */
/* s = 0x1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 (from "2^384") */
/* c = [(340282366920938463463374607431768211456, 1), (79228162514264337593543950336, 1), (4294967296, -1), (1, 1)] (from "2^128,1;2^96,1;2^32,-1;1,1") */
/* machine_wordsize = 32 (from "32") */
/*                                                                    */
/* NOTE: In addition to the bounds specified above each function, all */
/*   functions synthesized for this Montgomery arithmetic require the */
/*   input to be strictly less than the prime modulus (s-c), and also */
/*   require the input to be in the unique saturated representation.  */
/*   All functions also ensure that these two properties are true of  */
/*   return values.                                                   */

#include <stdint.h>
typedef unsigned char fiat_p384_uint1;
typedef signed char fiat_p384_int1;
: Value not < (m ≤ eval saturated_upper_bounds) : expected 39402006196394479212279040100143613805079739270465446667948293404245721771497210611414266254884915640806627990306815 < 39402006196394479212279040100143613805079739270465446667948293404245721771496870329047266088258938001861606973112319

