(* This file is autogenerated from CurveParameters.v by remake_packages.py *)
Require Export Crypto.Specific.Framework.CurveParameters.

Module Type CurveParametersPrePackage.
  Parameter CurveParameters_package' : { T : _ & T }.
  Parameter CurveParameters_package : projT1 CurveParameters_package'.
End CurveParametersPrePackage.

Module MakeCurveParametersTest (PKG : CurveParametersPrePackage).
  Ltac get_MakeCurveParametersTest_package _ := eval hnf in PKG.CurveParameters_package.
  Ltac CurveParameters_reduce_proj x :=
    eval cbv beta iota zeta in x.

  Ltac get_sz _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in sz).
  Notation sz := (ltac:(let v := get_sz () in exact v)) (only parsing).
  Ltac get_bitwidth _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in bitwidth).
  Notation bitwidth := (ltac:(let v := get_bitwidth () in exact v)) (only parsing).
  Ltac get_s _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in s).
  Notation s := (ltac:(let v := get_s () in exact v)) (only parsing).
  Ltac get_c _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in c).
  Notation c := (ltac:(let v := get_c () in exact v)) (only parsing).
  Ltac get_carry_chains _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in carry_chains).
  Notation carry_chains := (ltac:(let v := get_carry_chains () in exact v)) (only parsing).
  Ltac get_a24 _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in a24).
  Notation a24 := (ltac:(let v := get_a24 () in exact v)) (only parsing).
  Ltac get_coef_div_modulus _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in coef_div_modulus).
  Notation coef_div_modulus := (ltac:(let v := get_coef_div_modulus () in exact v)) (only parsing).
  Ltac get_goldilocks _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in goldilocks).
  Notation goldilocks := (ltac:(let v := get_goldilocks () in exact v)) (only parsing).
  Ltac get_montgomery _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in montgomery).
  Notation montgomery := (ltac:(let v := get_montgomery () in exact v)) (only parsing).
  Ltac get_modinv_fuel _ := let pkg := get_MakeCurveParametersTest_package () in CurveParameters_reduce_proj (let '(sz, bitwidth, s, c, carry_chains, a24, coef_div_modulus, goldilocks, montgomery, modinv_fuel) := pkg in modinv_fuel).
  Notation modinv_fuel := (ltac:(let v := get_modinv_fuel () in exact v)) (only parsing).
End MakeCurveParametersTest.
